<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * PostRepository constructor.
     * @param EntityManagerInterface $em
     * @param Mapping\ClassMetadata|null $metaData
     */
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(Post::class):
                $metaData
        );
    }

    public function insert(Post $post){
        try {
            $this->_em->persist($post);
            $this->_em->flush($post);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    public function update(Post $post){
        try {
            $this->_em->merge($post);
            $this->_em->flush($post);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    public function remove(Post $post){
        try {
            $this->_em->remove($post);
            $this->_em->flush($post);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
