<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Question;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(Question::class):
            $metaData);
    }

    /**
     * @param Question $comment
     * @return bool
     * @throws \Doctrine\ORM\ORMException
     */
    public function insert(Question $comment){
        try {
            $this->_em->persist($comment);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
